"""Add birthdate to User

Revision ID: 387bf91d8d94
Revises: da4d3e502d80
Create Date: 2026-09-29 13:34:54.053150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387bf91d8d94'
down_revision: Union[str, Sequence[str], None] = 'da4d3e502d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
